<a href="https://colab.research.google.com/github/zhaotianjing/ASA_workshop/blob/main/2024_Mixed_Models_for_Agricultural_Science_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Create a 1D array**

#### Explicitly define the values
Use `[]` to represent a list (array)

In [ ]:
# create a list (array)
array = [1, 2, 3, 4]
print(array)

[1, 2, 3, 4]


`np.array()`: instantiate a NumPy array (https://numpy.org/doc/stable/reference/generated/numpy.array.html)

In [ ]:
# assign the list to a NumPy array
array = [1, 2, 3, 4]
array_np = np.array(array)
# it is equivalent
array_np = np.array([1, 2, 3, 4])
# print the result
print(array_np)

[1 2 3 4]


#### All-zero or all-one vectors/matrices
<center><img src="https://github.com/vt-ads/intro_to_phenomics/blob/main/res/l01/mask.png?raw=1" width="800"/></center>

`np.zeros()`: create an array of all zeros (https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

`np.ones()`: create an array of all zeros (https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

This technique is very useful when you want to generate a binary vector/matrix to indicate signals of interest.

In [ ]:
array_zeros = np.zeros(4)
print(array_zeros)

[0. 0. 0. 0.]


In [ ]:
array_ones = np.ones(4)
print(array_ones)

[1. 1. 1. 1.]


#### Arithmetic sequence
`np.arange()`: create a sequence defined by an interval
(https://numpy.org/doc/stable/reference/generated/numpy.arange.html)

`np.linspace()`: create a sequence defined by a size (https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

A way to subset (downsample) a dataset or an image.
<center><img src="https://github.com/vt-ads/intro_to_phenomics/blob/main/res/l01/downsample.png?raw=1" width="1000"/></center>


In [ ]:
# np.arange(start, stop, interval)
array_seq_interval = np.arange(1, 10, 2.5)
print(array_seq_interval)

[1.  3.5 6.  8.5]


In [ ]:
# np.linspace(start, stop, size)
array_seq_size = np.linspace(1, 10, 4)
print(array_seq_size)

[ 1.  4.  7. 10.]


#### Exercise 2
Create an array with the same elements `[5, 10, 15, 20]` using two different functions: `np.linspace()` and `np.arange()`

array_A  [ 5. 10. 15. 20.]
array_B  [ 5 10 15 20]


### **Multi-dimensional matrix**
NumPy is also capable of dealing with N-dimensional data structure. Here we will introduce several ways to create an N-dimensional matrix.

Explicitly assign values to create a 2D matirx

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


#### Shape
In Python, `Shape` is an important component used to describe the dimension of a matrix. `Shape` in Python can be defined by a tuple, `()`.

`np.shape()`: examine the matrix dimension (https://numpy.org/doc/stable/reference/generated/numpy.shape.html)

In [ ]:
# (row, column)
print("Matrix\n", A)
print("\n")
print("Shape: ", A.shape)

Matrix
 [[1 2 3]
 [4 5 6]]


Shape:  (2, 3)


Create a all-zero or all-one nd-matrix by assigning the dimension (`shape`).

In [ ]:
# shape: (row, column)
shape = (2, 3)
B = np.zeros(shape)
print("B\n", B)

# shape: (row, column, channel)
C = np.ones((2, 3, 4))
print("C\n", C)

B
 [[0. 0. 0.]
 [0. 0. 0.]]
C
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In a convolutional neural network, flattening a matrix is a common approach to turn an image matrix into a regression vector.

<center><img src="https://github.com/vt-ads/intro_to_phenomics/blob/main/res/l01/cnn.png?raw=1" width="800"/></center>

<center><img src="https://github.com/vt-ads/intro_to_phenomics/blob/main/res/l01/flatten.png?raw=1" width="800"/></center>


`np.reshape()`: a handy function to turn a one-dimension array to a two-dimension matrix.
(https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

`np.flatten()`: "flatten" the matrix back to a one-dimension array using the function (https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html)


In [ ]:
# create a 1D array with 6 elements
a = np.array([1, 2, 3, 4, 5, 6])
print("'a'\n", a)

# reshape it into a 2D array, with 2 rows and 3 columns
a_reshape = a.reshape((2, 3))
print("\nReshaped 'a' (2x3)\n", a_reshape)

'a'
 [1 2 3 4 5 6]

Reshaped 'a' (2x3)
 [[1 2 3]
 [4 5 6]]
