<a href="https://colab.research.google.com/github/zhaotianjing/ASA_workshop/blob/main/2024_Mixed_Models_for_Agricultural_Science_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Basic Matrix Algebra

## 1.1 Notation for Scalars, Vectors, and Matrices



- Lowercase letters represent scalars, for example: $x$, $b$

- Boldface, lowercase letters represent vectors, for example: $\mathbf{x}$, $ \mathbf{y}$

- Boldface, uppercase letters represent matrices, for example: $ \mathbf{X} $, $ \mathbf{A}$

## 1.2 Notation for Dimensions and Elements of a Matrix

* Suppose $ \mathbf{A} $ is a matrix with $ m $ rows and $ n $ columns. Then we say that $\mathbf{A} $ has dimensions $ m \times n $.

* Let $ a_{ij} \in \mathbb{R} $ be the element or entry in the $ i $th row and $ j $th column of $ \mathbf{A} $.

* We convey all this information with the notation $ \mathbf{A} = [a_{ij}] $.

## 1.3 The Product of a Scalar and a Matrix


Suppose $ \mathbf{A} = [a_{ij}] $ is a matrix of dimension $ m \times n $. For any scalar $ c \in \mathbb{R} $, $$ c\mathbf{A} = \mathbf{A}c = [ca_{ij}] $$

i.e., the product of the scalar $ c $ and the matrix $ \mathbf{A} = [a_{ij}] $ is the matrix whose entry in the $ i $th row and $ j $th column is $ c $ times $a_{ij} $ for each $ i = 1, ..., m $ and $ j = 1, ..., n $.

In [ ]:
A = matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = TRUE) # Define a matrix A
c = 2                                                       # Define a scalar c
A2 = c * A                                                  # Compute the product of the scalar and the matrix
A2                                                          # This will display the resulting matrix

[,1] [,2]
[1,] 2    4   
[2,] 6    8

R code:

A <- matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = TRUE)  # Define a matrix A
A
c <- 2                                                        # Define a scalar c
A2 <- c * A                                                   # Compute the product of the scalar and the matrix
A2                                                            # This will display the resulting matrix

A <- matrix(c(1, 2, 6, 3, 4, 9), nrow = 2, ncol = 3, byrow = TRUE)  # Define a new matrix A
A


B <- matrix(c(1, 3, 5, 7), nrow = 2, ncol = 2, byrow = TRUE)  # Define a matrix B
b <- 3                                                        # Define a scalar b
b * B                                                         # Compute the product of the scalar and the matrix


In [ ]:
A = matrix(c(1, 2, 3, 4, 5, 6), nrow = 2, ncol = 3, byrow = TRUE)  # Define a matrix A
A

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

Question:

Create a 2x2 matrix $\mathbf{B}$:

$
\mathbf{B} = \begin{bmatrix}
1 & 3 \\
5 & 7 \\
\end{bmatrix}
$

and a scalar $b = 3$.

Write code to compute the product of the scalar $b$ and the matrix $\mathbf{B}$.


[,1] [,2]
[1,]  3    9  
[2,] 15   21

## 1.4 The Sum of Two Matrices

Suppose $\mathbf{A} = [a_{ij}]$ and $\mathbf{B} = [b_{ij}] $ are matrices of dimension $m \times n $. Then the sum of $\mathbf{A} $ and $ \mathbf{B} $ is another matrix $\mathbf{C} = [c_{ij}] $ of the same dimension, where:

$$ \mathbf{C} = \mathbf{A} + \mathbf{B} = [a_{ij} + b_{ij}] $$

i.e., the entry in the $i$th row and $j$th column of $\mathbf{C} $ is the sum of the entry in the $i$th row and $j$th column of $\mathbf{A}$ and the entry in the $i$th row and $j$th column of $\mathbf{B}$.

In [ ]:
A = matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = TRUE) # Define a matrix A
B = matrix(c(5, 6, 7, 8), nrow = 2, ncol = 2, byrow = TRUE) # Define a matrix B
C = A + B # Compute the sum of the two matrices
C # This will display the resulting matrix

[,1] [,2]
[1,]  6    8  
[2,] 10   12

Question:

Create two 2x3 matrices $\mathbf{A}$ and $\mathbf{B}$:

$
\mathbf{A} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6 \\
\end{bmatrix}
$

$
\mathbf{B} = \begin{bmatrix}
1 & 1 & 1 \\
2 & 2 & 2 \\
\end{bmatrix}
$

Write code to compute the sum of the matrices $\mathbf{A}$ and $\mathbf{B}$.

[,1] [,2] [,3]
[1,] 2    3    4   
[2,] 6    7    8

## 1.5 Vector and Vector Transpose

A vector is a matrix with one column, denoted as:

$$ \mathbf{x} = \begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{bmatrix} $$

The transpose of a vector $ \mathbf{x} $ is a matrix with one row, denoted as:

$$ \mathbf{x}^T = [x_1, x_2, \dots, x_n] $$

i.e., $\mathbf{x}$ is a matrix with one column and $\mathbf{x}^T$ is the matrix with the same entries as $\mathbf{x}$ but written as a row rather than a column.

In [ ]:
x = matrix(c(1, 2, 3), nrow = 3, ncol = 1) # Define a column vector x
dim(x)  # This will display the dimensions of x

[1] 3 1

In [ ]:
x_T = t(x) # Compute the transpose of the vector x
x_T # This will display the vector and its transpose

[,1] [,2] [,3]
[1,] 1    2    3

In [ ]:
dim(x_T)

[1] 1 3

 Question:

Given a 1x3 row vector **y**:

$
\mathbf{y} = \begin{bmatrix}
1 & 2 & 3
\end{bmatrix}
$

Write code to compute the transpose of the vector **y**.


[,1] [,2] [,3]
[1,] 1    2    3

In [ ]:
dim(y)

[1] 1 3

In [ ]:
t(y)

[,1]
[1,] 1   
[2,] 2   
[3,] 3

## 1.6 Transpose of a Matrix

Suppose $\mathbf{A}$ is an $m \times n $ matrix. Then the transpose of the matrix $\mathbf{A}$, denoted as $\mathbf{A}^T$, is obtained by interchanging the rows and columns of $\mathbf{A}$.

If we write $ \mathbf{A} = [\mathbf{a}_1; ...; \mathbf{a}_n]$, where $\mathbf{a}_i $ is the $i$th column of $\mathbf{A}$ for each $i = 1, ..., n $, then:

$$ \mathbf{A}^T = \begin{bmatrix} \mathbf{a}_1^T \\ ... \\ \mathbf{a}_n^T \end{bmatrix} $$

In [ ]:
A = matrix(c(1, 2, 3, 4, 5, 6), nrow = 3, ncol = 2, byrow = TRUE) # Define a matrix A
A_T = t(A)  # Compute the transpose of the matrix A
print(A)
print(A_T)  # This will display the matrix and its transpose

     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


Question:

Create a 2x4 matrix **B**:

$
\mathbf{B} = \begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8\\
\end{bmatrix}
$

Write code to compute the transpose of the matrix.


[,1] [,2] [,3] [,4]
[1,] 1    2    3    4   
[2,] 5    6    7    8

In [ ]:
dim(B) # This will display the dimensions of B

[1] 2 4

In [ ]:
t(B) # Compute and display the transpose of B

[,1] [,2]
[1,] 1    5   
[2,] 2    6   
[3,] 3    7   
[4,] 4    8

## 1.7 Matrix Multiplication

Suppose $\mathbf{A} = [a_{ij}]$ is an $m \times n$ matrix and $\mathbf{B} = [b_{ij}]$ is an $n \times k$ matrix.

Then the matrix product $\mathbf{AB}$, denoted as $ \mathbf{C} = [c_{ij}]$, is an $m \times k$ matrix where:

$$ c_{ij} = \sum_{l=1}^{n} a_{il} b_{lj} $$

i.e., each element $c_{ij}$ of the matrix $\mathbf{C}$ is computed as the sum of the product of corresponding elements from the $i$th row of $\mathbf{A}$ and the $j$th column of $\mathbf{B}$.

In [ ]:
A = matrix(c(1, 2, 3, 4, 5, 6), nrow = 3, ncol = 2, byrow = TRUE)# Define a matrix A
B = matrix(c(2, 3, 4, 5), nrow = 2, ncol = , byrow = TRUE) # Define a matrix B
A
B

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6

[,1] [,2]
[1,] 2    3   
[2,] 4    5

In [ ]:
C = A %*% B  # Compute the matrix product AB
C  # This will display the resulting matrix

[,1] [,2]
[1,] 10   13  
[2,] 22   29  
[3,] 34   45

Question:

Given a 2x3 matrix **A**:

$
\mathbf{A} = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
\end{bmatrix}
$

and a 3x1 matrix **B**:

$
\mathbf{B} = \begin{bmatrix}
2 \\
3 \\
4 \\
\end{bmatrix}
$

Write a code to compute the matrix product of **A** and **B**.


[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

[,1]
[1,] 2   
[2,] 3   
[3,] 4

In [ ]:
A %*% B

[,1]
[1,] 20  
[2,] 47

## 1.8 Transpose of a Matrix Product



The transpose of a matrix product is a product of the transposes
in reverse order; i.e., $(\mathbf{AB})^T = \mathbf{B}^T \mathbf{A}^T$.

Question: write code to verify $(\mathbf{AB})^T = \mathbf{B}^T \mathbf{A}^T$

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

[,1]
[1,] 2   
[2,] 3   
[3,] 4

In [ ]:
 t(A %*% B)

[,1] [,2]
[1,] 20   47

In [ ]:
t(B) %*% t(A)

[,1] [,2]
[1,] 20   47

## 1.9 Zero and One Vectors and the Identity Matrix

- Zero Vector, $\mathbf{0} $:
  $$\mathbf{0} = \begin{bmatrix} 0 \\ 0 \\ \vdots \\ 0 \end{bmatrix} $$
  $\mathbf{0}$ is also used to denote a matrix whose entries are all zero.
- One Vector, $\mathbf{1}$:
  $$\mathbf{1} = \begin{bmatrix} 1 \\ 1 \\ \vdots \\ 1 \end{bmatrix} $$
- Identity Matrix, $\mathbf{I}$:
  $$ I = \begin{bmatrix} 1 & 0 & 0 & \dots & 0 \\ 0 & 1 & 0 & \dots & 0 \\ 0 & 0 & 1 & \dots & 0 \\ \vdots & \vdots & \vdots & \ddots & \vdots \\ 0 & 0 & 0 & \dots & 1 \end{bmatrix} $$




In [ ]:
# Creating Zero Vector
zero_vector = numeric(5) #or rep(0, 5)
zero_vector

[1] 0 0 0 0 0

In [ ]:
# Creating One Vector
one_vector = rep(1, 5)
one_vector

[1] 1 1 1 1 1

In [ ]:
# Creating Identity Matrix
identity_matrix = diag(5)
identity_matrix

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    1    0    0    0   
[3,] 0    0    1    0    0   
[4,] 0    0    0    1    0   
[5,] 0    0    0    0    1

In [ ]:
A

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [ ]:
A %*% numeric(3)

[,1]
[1,] 0   
[2,] 0

In [ ]:
A %*% rep(1, 3)

[,1]
[1,]  6  
[2,] 15

In [ ]:
A %*% diag(3)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

## 1.10 Square Matrices

- A matrix $\mathbf{A}$ is said to be **square** if and only if $m = n$.
- If $\mathbf{A}$ is an $m \times n$ matrix, then $\mathbf{A}^T \mathbf{A}$ is an $n \times n $ matrix.
  - Thus, $\mathbf{A}^T \mathbf{A}$ is a square matrix for any matrix $\mathbf{A}$.

## 1.11 Inverse of a Matrix

- A square matrix $\mathbf{A}$ is **nonsingular** or **invertible** if and only if there exists a square matrix $\mathbf{B}$ such that $\mathbf{AB} = \mathbf{I}$.
- If $\mathbf{A}$ is nonsingular and $\mathbf{AB} = \mathbf{I}$, then $\mathbf{B}$ is the unique **inverse** of $\mathbf{A}$ and is written as $\mathbf{A}^{-1}$.
- For a nonsingular matrix $\mathbf{A}$, we have $\mathbf{AA}^{-1} = \mathbf{I}$. (It is also true that $\mathbf{A}^{-1}\mathbf{A} = \mathbf{I}$)
- A square matrix without an inverse is called **singular**.
- An $n \times n$ matrix $\mathbf{A}$ is singular if and only if $\text{rank}(\mathbf{A}) < n$.


In [ ]:
A = matrix(c(2, 3, 1, 4), nrow = 2, ncol = 2, byrow = TRUE) # Creating a nonsingular (invertible) matrix A
A_inverse = solve(A) # Calculating the inverse of matrix A; if matrix is singular - error "LinAlgError: Singular matrix"
A
A_inverse

[,1] [,2]
[1,] 2    3   
[2,] 1    4

[,1] [,2]
[1,]  0.8 -0.6
[2,] -0.2  0.4

In [ ]:
# Verifying that A * A_inverse = I and A_inverse * A = I
A %*% A_inverse  # should be the identity matrix

[,1] [,2]         
[1,] 1    -1.110223e-16
[2,] 0     1.000000e+00

In [ ]:
A_inverse %*% A

[,1] [,2]
[1,] 1    0   
[2,] 0    1

Question:

You are given a 2x2 nonsingular (invertible) matrix **A**:

$
\mathbf{A} = \begin{bmatrix}
3 & 5 \\
2 & 6 \\
\end{bmatrix}
$

Write code to compute the inverse of the matrix **A**. Verify your results.


[,1] [,2]
[1,] 3    5   
[2,] 2    6

In [ ]:
A_inverse = solve(A)
A_inverse

[,1]  [,2]  
[1,]  0.75 -0.625
[2,] -0.25  0.375

In [ ]:
A_inverse %*% A

[,1]         [,2]        
[1,] 1.000000e+00 6.661338e-16
[2,] 1.110223e-16 1.000000e+00

# Acknowledgment




Reference:
1. STAT 510 Lecture Notes, Iowa State University
2. STAT 206 Lecture Notes, University of California, Davis
3. SISG - Introduction to Mixed Model, Guilherme J. M. Rosa, University of Wisconsin-Madison
4. lmmonboard: https://lmmonboard.ucdavis.edu/myapp, Hao Cheng, Chunpeng James Chen

Contributors:
* Tianjing Zhao (tzhao9@unl.edu), University of Nebraska-Lincoln
* Brian Rice (brice7@unl.edu), University of Nebraska-Lincoln
* Hao Cheng (qtlcheng@ucdavis.edu), University of California, Davis
* GPT-4

# 2. Images as Matrices